Boxer.UI/Controllers/CSVOrdersController.cs
using Boxer.UI.Models;
using CsvHelper;
using CsvHelper.Configuration;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace Boxer.UI.Controllers
{
    public class CSVOrdersController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        // Constructor to initialize IHttpClientFactory
        public CSVOrdersController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        // Action to render the upload CSV view
        public IActionResult UploadCsv()
        {
            return View();
        }

        private CsvConfiguration GetCsvConfiguration()
        {
            return new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                Delimiter = ";", // Use semicolon as the delimiter
                HeaderValidated = null, // Disable header validation
                MissingFieldFound = null // Disable missing field validation
            };
        }

        //Method to handle the reading of the CSV file and converts it to a list of CsvOrders records
        private List<CsvOrders> ReadCsvOrders(IFormFile file)
        {
            using (var reader = new StreamReader(file.OpenReadStream()))
            using (var csv = new CsvReader(reader, GetCsvConfiguration()))
            {
                return csv.GetRecords<CsvOrders>().ToList();
            }
        }

        // Action to handle the CSV file upload
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadCsv(IFormFile file)
        {
            // Check if a file was selected and is not empty
            if (file == null || file.Length == 0)
            {
                ModelState.AddModelError("", "CSV is empty or not selected.");
                return View();
            }

            var validOrders = new List<CsvOrders>();
            var errors = new List<string>();

            try
            {
                //Read the CSV records
                var ordersCsv = ReadCsvOrders(file);

                foreach (var order in ordersCsv)
                {
                    //Validates each record and collects valid orders and errors
                    if (TryValidateModel(order))
                    {
                        validOrders.Add(order);
                    }
                    else
                    {
                        errors.AddRange(ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                    }
                }
            }
            catch (CsvHelperException ex)
            {
                // Handle exceptions during CSV reading and parsing
                ModelState.AddModelError("", $"There is an invalid field in this order: {ex.Context.Parser.RawRecord}");
                return View();
            }


            // If there are any validation errors, redirect to the error message
            if (errors.Any())
            {
                TempData["ErrorMessage"] = "Some records have errors. Please correct them and try again.";
                return RedirectToAction("UploadCsv");
            }

            var orderNumbers = new List<int>();

            // Submit each valid order and collect the generated OrderNumbers
            foreach (var order in validOrders)
            {
                var orderNumber = await SubmitOrderAsync(order);
                if (orderNumber.HasValue)
                {
                    orderNumbers.Add(orderNumber.Value);
                }
            }

            // Display the success message with the generated OrderNumbers
            TempData["SuccessMessage"] = "Orders successfully processed. Generated Order Numbers: " + string.Join(", ", orderNumbers);
            return RedirectToAction("UploadCsv");
        }


        // Method to submit an order and return the generated OrderNumber
        private async Task<int?> SubmitOrderAsync(CsvOrders order)
        {
            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.PostAsJsonAsync("api/Orders", order);

                if (response.IsSuccessStatusCode)
                {
                    var createdOrder = await response.Content.ReadFromJsonAsync<Orders>();
                    return createdOrder?.OrderNumber;
                }
                else
                {
                    var errorContent = await response.Content.ReadAsStringAsync();
                    TempData["ErrorMessage"] = "An error occurred while submitting your order. Please try again later.";
                }

            }
            catch (HttpRequestException ex)
            {
                Console.WriteLine($"HttpRequestException: {ex.Message}");

                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "Unable to reach the server. Please check your internet connection and try again.";
                }
                else
                {
                    TempData["ErrorMessage"] = "An unexpected error occurred while submitting your order. Please try again later.";
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
                TempData["ErrorMessage"] = "An unexpected error occurred. Please try again later.";
            }
            return null;
        }
    }
}

Boxer.UI/Controllers/OrdersController.cs
using Boxer.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace Boxer.UI.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public OrdersController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            if (TempData.ContainsKey("GeneratedOrderNumber"))
            {
                int generatedOrderNumber = (int)TempData["GeneratedOrderNumber"]!;
                ViewBag.GeneratedOrderNumber = generatedOrderNumber;
            }

            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.GetFromJsonAsync<List<Orders>>("api/Orders");

                if (response != null)
                {
                    return View(response);
                }
                else
                {
                    TempData["ErrorMessage"] = "No data available.";
                    return RedirectToAction("Error");
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "API is currently unavailable.";
                    return RedirectToAction("Error");
                }
                else
                {
                    TempData["ErrorMessage"] = ex.Message.ToString();
                    return RedirectToAction("Error");
                }
            }
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.GetFromJsonAsync<Orders>($"api/Orders/{id}");

                if (response != null)
                {
                    return View(response);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "API is currently unavailable.";
                    return RedirectToAction("Error");
                }
                else
                {
                    TempData["ErrorMessage"] = ex.Message.ToString();
                    return RedirectToAction("Error");
                }
            }
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            var model = new Orders();
            return View(model);
        }

        // POST: Orders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Orders orders)
        {
            if (!ModelState.IsValid)
            {
                return View(orders); // Return the view with the validation errors
            }

            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.PostAsJsonAsync("api/Orders", orders);

                if (response.IsSuccessStatusCode)
                {
                    // Extract OrderNumber from the response
                    var createdOrder = await response.Content.ReadFromJsonAsync<Orders>();
                    if (createdOrder != null)
                    {
                        TempData["GeneratedOrderNumber"] = createdOrder.OrderNumber;
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["ErrorMessage"] = "Error creating Order. Please try again.";
                    return RedirectToAction("Error");
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "API is currently unavailable.";
                    return RedirectToAction("Error");
                }
                else
                {
                    TempData["ErrorMessage"] = ex.Message.ToString();
                    return RedirectToAction("Error");
                }
            }
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.GetFromJsonAsync<Orders>($"api/Orders/{id}");

                if (response != null)
                {
                    return View(response);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "API is currently unavailable.";
                    return RedirectToAction("Error");
                }
                else
                {
                    TempData["ErrorMessage"] = ex.Message.ToString();
                    return RedirectToAction("Error");
                }
            }
        }

        // POST: Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Orders orders)
        {
            if (id != orders.OrderID)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(orders); // Return the view with the validation errors
            }

            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.PutAsJsonAsync($"api/Orders/{id}", orders);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["ErrorMessage"] = "Error updating Order. Please try again.";
                    return RedirectToAction("Error");
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "API is currently unavailable.";
                    return RedirectToAction("Error");
                }
                else
                {
                    TempData["ErrorMessage"] = ex.Message.ToString();
                    return RedirectToAction("Error");
                }
            }
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.GetFromJsonAsync<Orders>($"api/Orders/{id}");

                if (response != null)
                {
                    return View(response);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "API is currently unavailable.";
                    return RedirectToAction("Error");
                }
                else
                {
                    TempData["ErrorMessage"] = ex.Message.ToString();
                    return RedirectToAction("Error");
                }
            }
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.DeleteAsync($"api/Orders/{id}");

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["ErrorMessage"] = "Error deleting Order. Please try again.";
                    return RedirectToAction("Error");
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.InnerException is System.Net.Sockets.SocketException)
                {
                    TempData["ErrorMessage"] = "API is currently unavailable.";
                    return RedirectToAction("Error");
                }
                else
                {
                    TempData["ErrorMessage"] = ex.Message.ToString();
                    return RedirectToAction("Error");
                }
            }
        }

        private async Task<bool> OrdersExistsAsync(int id)
        {
            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var response = await client.GetFromJsonAsync<Orders>($"api/Orders/{id}");
                return response != null;
            }
            catch (HttpRequestException)
            {
                return false;
            }
        }

        // Error action to display error messages
        public IActionResult Error()
        {
            var errorMessage = TempData["ErrorMessage"] as string;

Boxer.UI/Controllers/OrdersFilterController.cs
using Boxer.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace Boxer.UI.Controllers
{
    public class OrdersFilterController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public OrdersFilterController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        // GET: Orders
        public async Task<IActionResult> Index(
            int? startOrderNumber = null,
            int? endOrderNumber = null,
            string? supplierName = null,
            DateTime? startDate = null,
            DateTime? endDate = null
        )
        {
            // Return the values that the user entered before pressing filter
            ViewData["StartOrderNumber"] = startOrderNumber;
            ViewData["EndOrderNumber"] = endOrderNumber;
            ViewData["StartDate"] = startDate?.ToString("yyyy-MM-dd");
            ViewData["EndDate"] = endDate?.ToString("yyyy-MM-dd");
            ViewData["SupplierName"] = supplierName;

            var client = _httpClientFactory.CreateClient("Boxer.API");

            try
            {
                var url = $"api/Orders?startOrderNumber={startOrderNumber}&endOrderNumber={endOrderNumber}&supplierName={supplierName}&startDate={startDate:yyyy-MM-dd}&endDate={endDate:yyyy-MM-dd}";
                var response = await client.GetFromJsonAsync<List<Orders>>(url);

                if (response != null)
                {
                    return View(response);
                }
                else
                {
                    TempData["ErrorMessage"] = "No data available.";
                    return RedirectToAction("Error");
                }
            }
            catch (HttpRequestException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Error");
            }
        }

        public IActionResult Error()
        {
            var errorMessage = TempData["ErrorMessage"] as string;
            var errorViewModel = new ErrorViewModel { ErrorMessage = errorMessage };
            return View(errorViewModel);
        }
    }
}

Boxer.UI/Views/Orders/Create.cshtml
@model Boxer.UI.Models.Orders

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Create an Order</h1>
<hr />

<form class="row m-0 pt-2" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="col-lg-5 mx-auto">
        <div class="form-floating mb-3">
            <input asp-for="Items" class="form-control" />
            <label asp-for="Items"></label>
            <span asp-validation-for="Items" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input asp-for="Quantity" class="form-control" />
            <label asp-for="Quantity"></label>
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input asp-for="Date" type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" />
            <label asp-for="Date"></label>
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input type="button" value="Back" onclick="history.back()" class="btn btn-danger" />
        </div>
    </div>
    <div class="col-lg-5 mx-auto">
        <div class="form-floating mb-3">
            <input asp-for="Price" class="form-control" />
            <label asp-for="Price"></label>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <select asp-for="Supplier" asp-items="Model.Suppliers" class="form-select"></select>
            <label asp-for="Supplier"></label>
            <span asp-validation-for="Supplier" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input asp-for="DeliveryDate" type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" />
            <label asp-for="DeliveryDate"></label>
            <span asp-validation-for="DeliveryDate" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input type="submit" value="Create" class="btn btn-primary float-end" />
        </div>
    </div>
</form>

Boxer.UI/Views/Orders/Delete.cshtml
@model Boxer.UI.Models.Orders

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this order?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Items)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Items)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderID" />
        <input onclick="history.back()" value="Back" class="btn btn-success" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

Boxer.UI/Views/Orders/Details.cshtml
@model Boxer.UI.Models.Orders

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Items)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Items)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>
    </dl>
</div>
<div>
    <input type="button" value="Back" onclick="history.back()" class="btn btn-danger" />
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.OrderID">Edit</a> 
    <a class="btn btn-danger float-end" asp-controller="OrdersExport" asp-action="ExportToPdf" asp-route-id="@Model?.OrderID">Export to PDF</a>
</div>

Boxer.UI/Views/Orders/Edit.cshtml
@model Boxer.UI.Models.Orders

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Edit Order @Html.DisplayFor(model => model.OrderNumber)</h1>
<hr />

<form class="row m-0 pt-2" asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="OrderID" />
    <input type="hidden" asp-for="OrderNumber" />
    <div class="col-lg-5 mx-auto">
        <div class="form-floating mb-3">
            <input asp-for="Items" class="form-control" />
            <label asp-for="Items"></label>
            <span asp-validation-for="Items" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input asp-for="Quantity" class="form-control" />
            <label asp-for="Quantity"></label>
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input asp-for="Date" type="date" class="form-control" />
            <label asp-for="Date"></label>
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input type="button" value="Back" onclick="location.href='@Url.Action("Index", "Orders")'" class="btn btn-danger" />
        </div>
    </div>
    <div class="col-lg-5 mx-auto">
        <div class="form-floating mb-3">
            <input asp-for="Price" class="form-control" />
            <label asp-for="Price"></label>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <select asp-for="Supplier" asp-items="Model.Suppliers" class="form-select"></select>
            <label asp-for="Supplier"></label>
        </div>
        <div class="form-floating mb-3">
            <input asp-for="DeliveryDate" type="date" class="form-control" />
            <label asp-for="DeliveryDate"></label>
            <span asp-validation-for="DeliveryDate" class="text-danger"></span>
        </div>
        <div class="form-floating mb-3">
            <input type="submit" value="Update" class="btn btn-success float-end" />
        </div>
    </div>
</form>

Boxer.UI/Views/Orders/Index.cshtml
@model IEnumerable<Boxer.UI.Models.Orders>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a class="btn btn-success" asp-action="Create">Create new order</a>
    <a class="btn btn-warning float-end" asp-controller="OrdersFilter">Filter Orders</a>
    <a class="btn btn-info float-end me-5" asp-controller="CSVOrders" asp-action="UploadCsv">Create order with CSV</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Supplier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Items)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    R @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Supplier)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryDate)
                </td>
                <td>
                    <a asp-action="Edit" class="text-success" asp-route-id="@item.OrderID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.OrderID">Details</a> |
                    <a asp-action="Delete" class="text-danger" asp-route-id="@item.OrderID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (ViewBag.GeneratedOrderNumber != null)
{
    <script>
        var generatedOrderNumber = @ViewBag.GeneratedOrderNumber;
        alert("Generated Order Number: " + generatedOrderNumber);
    </script>
}